/**/
// --------- weapons ---------

// pistols
#define REF_M9BERETTA					"beretta"
#define REF_COLT45						"colt45"
#define REF_USP							"usp"
#define REF_DESERTEAGLE					"deserteagle"
#define REF_DESERTEAGLEGOLD				"deserteaglegold"

// smg
#define REF_MP5							"mp5"
#define REF_SKORPION					"skorpion"
#define REF_UZI							"uzi"
#define REF_AK74U						"ak74u"
#define REF_P90							"p90"

// assault rifle
#define REF_AK47						"ak47"
#define REF_G3							"g3"
#define REF_G36C						"g36c"
#define REF_M16							"m16"
#define REF_M4							"m4"
#define REF_M14							"m14"
#define REF_MP44						"mp44"

// sniper rifle                                                                                            
#define REF_DRAGUNOVSVD					"dragunov"    
#define REF_M40A3						"m40a3"   
#define REF_BARRETT						"barrett"  
#define REF_REMINGTON700				"remington700"
#define REF_M21							"m21"              

// shotguns
#define REF_BENELLIM4					"m1014"
#define REF_WINCHESTER1200				"winchester1200"

// lmg
#define REF_RPD							"rpd"
#define REF_M249SAW						"saw"
#define REF_M60E4						"m60e4"

// grenades
#define REF_FRAG						"frag_grenade"
#define REF_CONCUSSION					"concussion_grenade"
#define REF_SMOKE_X1					"smoke_grenade"
#define REF_FLASH_X1					"flash_grenade"

// --------- specialty group 1 ----------
#define REF_PARABOLIC					"specialty_parabolic"
#define REF_GPSJAMMER					"specialty_gpsjammer"
#define REF_ARMORVEST					"specialty_armorvest"
#define REF_FRAG_X3						"specialty_fraggrenade"
#define REF_SPECIALGRENADE_X3			"specialty_specialgrenade"
#define REF_CLAYMORE_X2					"claymore_mp"
#define REF_C4_X2						"c4_mp"
#define REF_RPG_X2						"rpg_mp"

// --------- specialty group 2 ---------
#define REF_BULLETDAMAGE				"specialty_bulletdamage"
#define REF_BULLETPENETRATION			"specialty_bulletpenetration"
#define REF_BULLETACCURACY				"specialty_bulletaccuracy"
#define REF_ROF							"specialty_rof"
#define REF_FASTRELOAD					"specialty_fastreload"
#define REF_EXTRAAMMO					"specialty_extraammo"
#define REF_TWOPRIMARIES				"specialty_twoprimaries"

// --------- specialty group 3 ---------
#define REF_HOLDBREATH					"specialty_holdbreath"
#define REF_QUIETER						"specialty_quieter"
#define REF_LONGERSPRINT				"specialty_longersprint"
#define REF_DETECTEXPLOSIVE				"specialty_detectexplosive"
#define REF_EXPLOSIVEDAMAGE				"specialty_explosivedamage"
#define REF_PISTOLDEATH					"specialty_pistoldeath"
#define REF_GRENADEPULLDEATH			"specialty_grenadepulldeath"
#define REF_NULL						"specialty_null"

// ---------- CAMO ------------
#define REF_BLACKWHITEMARPAT			"camo_blackwhitemarpat"
#define REF_BROCKHUARD					"camo_brockhaurd"
#define REF_BUSHDWELLER					"camo_bushdweller"
#define REF_STAGGER						"camo_stagger"
#define REF_TIGERRED					"camo_tigerred"
#define REF_CAMO_NONE					"camo_none"
#define REF_GOLDEN						"camo_gold"

// --------- weapon attachments ----------
#define REF_GL							"gl"
#define REF_GRIP						"grip"
#define REF_SCOPE						"scope"
#define REF_ACOG						"acog"
#define REF_SUPPRESSOR					"silencer"
#define REF_REFLEX						"reflex"
#define REF_ATTACHMENT_NONE				"none"

